[build-system]
requires = ["setuptools>=62.6", "versioneer[toml]==0.28"]
build-backend = "setuptools.build_meta"

[project]
name = "pandas-expr"
description = "Lazy pandas API"
maintainers = [{name = "Patrick Hoefler", email = "patrick_hoefler@gmx.net"}]
license = {text = "BSD"}
keywords = ["pandas"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dask >= 2023.07",
    "pyarrow",
    "pandas >= 2",
]

dynamic = ["version"]

[project.urls]
"Source code" = "https://github.com/phofl/pandas-expr/"

[tool.setuptools.packages.find]
exclude = ["*tests*"]
namespaces = false

[tool.coverage.run]
omit = [
    "*/test_*.py",
]
source = ["pandas_expr"]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
]
ignore_errors = true

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "pandas_expr/_version.py"
versionfile_build = "pandas_expr/_version.py"
tag_prefix = "v"
parentdir_prefix = "pandas-"
