name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# Required shell entrypoint to have properly activated conda environments
defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Needed by codecov.io
      - name: Install Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/environment.yml
          environment-name: pandas-expr
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install Dask-Match
        run: python -m pip install -e . --no-deps

      - name: Run tests
        run: py.test --verbose --cov=pandas_expr --cov-report=xml

      - name: Coverage
        uses: codecov/codecov-action@v3
